pipeline {
    agent any

    tools{
        maven 'maven'
    }

    stages{
        stage('Build Maven'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/vtnhanhcmus/wikimedia-kafka-payment.git']])
                sh 'mvn clean install -DskipTests -Dspring-boot.build.skip=true'
            }
        }
        stage('Build docker image'){
            steps{
                script{
                    sh 'cd booking && docker build -t vtnhanhcmus/wiki-booking:latest .'
                }
            }
        }

        stage('Push Docker Hub') {
            steps {
                script{

                    withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
                        sh 'docker login -u vtnhanhcmus -p ${dockerhubpwd}'
                    }
                    sh 'docker push vtnhanhcmus/wiki-booking'
                }
            }
        }

    }
}