version: '3.9'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zoo1
    container_name: zoo1
    networks:
      - wiki-networks
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka1
    container_name: kafka1
    networks:
      - wiki-networks
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    networks:
      - wiki-networks
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:19092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zoo1
      - kafka1

  conduktor-platform:
    image: conduktor/conduktor-platform:1.17.3
    ports:
      - 8080:8080
    networks:
      - wiki-networks
    volumes:
      - conduktor_data:/var/conduktor
      - type: bind
        source: "./platform-config.yml"
        target: /opt/conduktor/platform-config.yaml
        read_only: true
    depends_on:
      - kafka1
      - kafka-schema-registry
    environment:
      CDK_IN_CONF_FILE: /opt/conduktor/platform-config.yaml
      KAFKA_BOOTSTRAP_SERVER: PLAINTEXT://kafka1:19092
      SR_SERVER: "http://kafka-schema-registry:8081"
      ORGANISATION_NAME: "default"
      CDK_ADMIN_EMAIL: "admin@conduktor.io"
      CDK_ADMIN_PASSWORD: "admin"

  wiki-media-request:
      image: vtnhanhcmus/wikimedia-request
      ports:
        - "8085:8085"
      networks:
        - wiki-networks
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://wiki-media-mysql:3306/wikimedia?useUnicode=true&characterEncoding=utf-8&&allowLoadLocalInfile=true
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:19092
      depends_on:
        - kafka1
        - kafka-schema-registry
        - wiki-media-mysql
      deploy:
        resources:
          limits:
            memory: 1400MB
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s

  wiki-media-payment:
    image: vtnhanhcmus/wikimedia-payment
    ports:
      - "8088:8088"
    networks:
      - wiki-networks
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://wiki-media-mysql:3306/wikimedia?useUnicode=true&characterEncoding=utf-8&&allowLoadLocalInfile=true
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:19092
    depends_on:
      - kafka1
      - kafka-schema-registry
      - wiki-media-mysql
    deploy:
      resources:
        limits:
          memory: 1400MB
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

  wiki-media-booking:
    image: vtnhanhcmus/wikimedia-booking
    ports:
      - "8086:8086"
    networks:
      - wiki-networks
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://wiki-media-mysql:3306/wikimedia?useUnicode=true&characterEncoding=utf-8&&allowLoadLocalInfile=true
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:19092
    depends_on:
      - kafka1
      - kafka-schema-registry
      - wiki-media-mysql
    deploy:
      resources:
        limits:
          memory: 1400MB
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

  wiki-media-mysql:
    container_name: wiki-media-mysql
    image: mysql:5.7
    platform: linux/amd64
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=wikimedia
    ports:
        - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

    volumes:
      - wiki-media-mysql:/var/lib/mysql
    networks:
      - wiki-networks


  jenkins:
    image: custom-jenkins-docker
    restart: always
    privileged: true
    user: root
    networks:
      - wiki-networks
    ports:
      - 9000:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock    

volumes:
  conduktor_data: {}
  wiki-media-mysql: {}
networks:
  wiki-networks:
