apiVersion: v1
kind: ConfigMap
metadata:
  name: wiki-configmap
data:
    SPRING_DATASOURCE_URL: jdbc:mysql://wiki-mysql-service:3306/wikimedia?useUnicode=true&characterEncoding=utf-8&&allowLoadLocalInfile=true
    SPRING_KAFKA_BOOTSTRAP_SERVERS: wiki-kafka-service:19092

    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: wikimedia

    ZOOKEEPER_CLIENT_PORT: "2181"
    ZOOKEEPER_SERVER_ID: "1"
    ZOOKEEPER_SERVERS: "wiki-zoo-service:2888:3888"

    KAFKA_ADVERTISED_LISTENERS: INTERNAL://wiki-kafka-service:19092,EXTERNAL://wiki-kafka-service:9092,DOCKER://host.docker.internal:29092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    KAFKA_ZOOKEEPER_CONNECT: "wiki-zoo-service:2181"
    KAFKA_BROKER_ID: "1"
    KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    KAFKA_JMX_PORT: "9999"
    KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
    KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

    SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://wiki-kafka-service:19092
    SCHEMA_REGISTRY_HOST_NAME: wiki-kafka-schema-registry-service
    SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

