apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-db-deployment
  labels:
    app: wiki-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-db
  template:
    metadata:
      labels:
        app: wiki-db
    spec:
      containers:
      - name: wiki-db
        image: kartoza/postgis:15-3.3
        resources:
          limits:
            memory: "1024Mi"  # Limit memory usage to 1024 megabytes
            cpu: "0.5"       # Limit CPU usage to 0.5 cores
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: wiki-configmap
              key: WIKI_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: wiki-configmap
              key: WIKI_USER
        - name: POSTGRES_PASS
          valueFrom:
            configMapKeyRef:
              name: wiki-configmap
              key: WIKI_PASS
--- 
apiVersion: v1
kind: Service
metadata:
  name: wiki-db-service
spec:
  selector:
    app: wiki-db
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432