apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-kafka-schema-registry-deployment
  labels:
    app: wiki-kafka-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-kafka-schema-registry
  template:
    metadata:
      labels:
        app: wiki-kafka-schema-registry
    spec:
      containers:
      - name: wiki-kafka-schema-registry
        image: confluentinc/cp-schema-registry:7.3.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"  # Limit memory usage to 1024 megabytes
            cpu: "0.5"       # Limit CPU usage to 0.5 cores
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: wiki-configmap
              key: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
        - name: SCHEMA_REGISTRY_HOST_NAME
          valueFrom:
            configMapKeyRef:
              name: wiki-configmap
              key: SCHEMA_REGISTRY_HOST_NAME
        - name: SCHEMA_REGISTRY_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: wiki-configmap
              key: SCHEMA_REGISTRY_LISTENERS
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-kafka-schema-registry-service
spec:
  selector:
    app: wiki-kafka-schema-registry
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
