apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-request-deployment
  labels:
    app: wiki-request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-request
  template:
    metadata:
      labels:
        app: wiki-request
    spec:
      containers:
      - name: wiki-request
        image: vtnhanhcmus/wiki-booking:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"  # Limit memory usage to 1024 megabytes
            cpu: "0.5"       # Limit CPU usage to 0.5 cores
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: wiki-configmap
              key: SPRING_DATASOURCE_URL
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom: 
            configMapKeyRef:
              name: wiki-configmap
              key: SPRING_KAFKA_BOOTSTRAP_SERVERS
       
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-request-service
spec:
  selector:
    app: wiki-request
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
